/**
 * Persistent Memory Vault Automatic Indexer for STONICX
 * 
 * Manages markdown file synchronization (`MEMORY.md`, `DAILY-NOTE.md`, `VAULT-INDEX.md`)
 * and bidirectional technical recall across sessions.
 */

import {
  StonicxUserProfile,
  StonicxTopicNote,
  StonicxDailyLog,
  StonicxJobPriming
} from '../../types/stonicxMemory';
import {
  loadStonicxProfile,
  loadStonicxTopicNotes,
  loadStonicxDailyLogs,
  loadStonicxJobs,
  saveStonicxTopicNotes,
  saveStonicxDailyLogs,
  getTodayString
} from '../../utils/stonicxMemoryStore';

export interface VaultIndexResult {
  memoryMd: string;
  dailyNoteMd: string;
  vaultIndexMd: string;
  indexedTimestamp: number;
  totalNotes: number;
  totalLogs: number;
}

export class StonicxMemoryIndexer {
  private static STORAGE_KEY_MEMORY_MD = 'stonicx_file_memory_md';
  private static STORAGE_KEY_DAILY_MD = 'stonicx_file_daily_note_md';
  private static STORAGE_KEY_INDEX_MD = 'stonicx_file_vault_index_md';

  /**
   * Generates and automatically indexes all session state into MEMORY.md, DAILY-NOTE.md, and VAULT-INDEX.md
   */
  public static autoIndexSessionState(): VaultIndexResult {
    const profile = loadStonicxProfile();
    const topicNotes = loadStonicxTopicNotes();
    const dailyLogs = loadStonicxDailyLogs();
    const jobs = loadStonicxJobs();

    // 1. Generate MEMORY.md
    const memoryMd = this.buildMemoryMd(profile, topicNotes, jobs);

    // 2. Generate DAILY-NOTE.md
    const dailyNoteMd = this.buildDailyNoteMd(dailyLogs);

    // 3. Generate VAULT-INDEX.md
    const vaultIndexMd = this.buildVaultIndexMd(topicNotes, dailyLogs, jobs);

    // Save to virtual markdown disk / localStorage
    if (typeof window !== 'undefined') {
      try {
        localStorage.setItem(this.STORAGE_KEY_MEMORY_MD, memoryMd);
        localStorage.setItem(this.STORAGE_KEY_DAILY_MD, dailyNoteMd);
        localStorage.setItem(this.STORAGE_KEY_INDEX_MD, vaultIndexMd);
      } catch (e) {
        console.warn('[MemoryVault] Local storage error writing markdown index:', e);
      }
    }

    console.log('[MemoryVault] Auto-indexed session state to MEMORY.md');

    return {
      memoryMd,
      dailyNoteMd,
      vaultIndexMd,
      indexedTimestamp: Date.now(),
      totalNotes: topicNotes.length,
      totalLogs: dailyLogs.length
    };
  }

  /**
   * Builds the formatted MEMORY.md document
   */
  public static buildMemoryMd(
    profile: StonicxUserProfile,
    topicNotes: StonicxTopicNote[],
    jobs: StonicxJobPriming[]
  ): string {
    const pinnedNotes = topicNotes.filter((n) => n.isPinned);
    const codeNotes = topicNotes.filter((n) => n.category === 'code');
    const projectNotes = topicNotes.filter((n) => n.category === 'project');

    return `# STONICX EXECUTIVE MEMORY VAULT (MEMORY.md)
*Auto-Indexed: ${new Date().toISOString()}*

---

## 1. USER & COMMANDER PROFILE
- **Commander Name**: ${profile.preferredName} (${profile.fullName})
- **Role / Title**: ${profile.roleOrTitle}
- **Organization / Core**: ${profile.organizationOrProject}
- **Communication Style**: ${profile.communicationStyle}
- **Bio**: ${profile.bioNotes}

### Preferred Languages & Technologies
- **Languages**: ${profile.preferredLanguages.join(', ')}
- **Tech Stack**: ${profile.techStack.join(', ')}

### Key Directives & Preferences
${profile.keyPreferences.map((p) => `- ${p}`).join('\n')}

---

## 2. PINNED ACTIVE BLUEPRINTS & ARCHITECTURES
${pinnedNotes.map((n) => `### 📌 ${n.title} [${n.category.toUpperCase()}]
${n.content}
*Tags: ${n.tags.join(', ')} | Modified: ${new Date(n.lastModified).toLocaleString()}*
`).join('\n\n')}

---

## 3. CODE GENERATION STANDARDS & REPOSITORIES
${codeNotes.map((n) => `### 💻 ${n.title}
${n.content}
`).join('\n\n')}

---

## 4. ACTIVE WORKFLOW PRIMING JOBS
${jobs.map((j) => `- **${j.name}** (\`${j.slug}\`): ${j.description} (Executions: ${j.usageCount})`).join('\n')}

---
*Generated by STONICX Memory Indexer Engine*
`;
  }

  /**
   * Builds the formatted DAILY-NOTE.md document
   */
  public static buildDailyNoteMd(dailyLogs: StonicxDailyLog[]): string {
    const today = getTodayString();
    return `# DAILY INTERACTION NOTES (DAILY-NOTE.md)
*Session Date: ${today}*

---

${dailyLogs.map((log) => `## 📅 Date: ${log.date} (Interactions: ${log.interactionCount})
- **Summary**: ${log.summary}
- **Topics Explored**: ${log.keyTopics.join(', ')}
- **Action Items**:
${log.actionItems.map((a) => `  - [x] ${a}`).join('\n')}
- **Last Sync**: ${new Date(log.timestamp).toLocaleTimeString()}
`).join('\n---\n\n')}
`;
  }

  /**
   * Builds the formatted VAULT-INDEX.md document
   */
  public static buildVaultIndexMd(
    topicNotes: StonicxTopicNote[],
    dailyLogs: StonicxDailyLog[],
    jobs: StonicxJobPriming[]
  ): string {
    const allTags = Array.from(new Set(topicNotes.flatMap((n) => n.tags)));

    return `# VAULT KNOWLEDGE GRAPH & DIRECTORY (VAULT-INDEX.md)

## 🗂️ TOPIC NOTES INDEX (${topicNotes.length} Entries)
| ID | Title | Category | Pinned | Last Modified |
| :--- | :--- | :--- | :---: | :--- |
${topicNotes.map((n) => `| \`${n.id}\` | ${n.title} | \`${n.category}\` | ${n.isPinned ? '✅' : '—'} | ${new Date(n.lastModified).toLocaleDateString()} |`).join('\n')}

---

## 🏷️ TAG CLOUD
${allTags.map((t) => `\`#${t}\``).join(' ')}

---

## ⚡ ACTIVE JOBS (${jobs.length} Pipelines)
${jobs.map((j) => `- \`${j.slug}\`: ${j.name} [Categories: ${j.targetCategories.join(', ')}]`).join('\n')}

---

## 📆 RECENT LOG TIMELINE
${dailyLogs.slice(0, 5).map((l) => `- **${l.date}**: ${l.summary} (${l.interactionCount} calls)`).join('\n')}
`;
  }

  /**
   * Bidirectional Recall: Queries vault markdown knowledge for relevant snippets given a prompt
   */
  public static queryVaultKnowledge(query: string, maxResults = 3): { title: string; snippet: string; category: string }[] {
    const notes = loadStonicxTopicNotes();
    const clean = query.toLowerCase();

    const matches = notes.filter((n) => {
      return (
        n.title.toLowerCase().includes(clean) ||
        n.content.toLowerCase().includes(clean) ||
        n.tags.some((t) => clean.includes(t.toLowerCase()))
      );
    });

    if (matches.length > 0) {
      return matches.slice(0, maxResults).map((m) => ({
        title: m.title,
        snippet: m.content.slice(0, 180),
        category: m.category
      }));
    }

    // Default pinned items
    return notes.filter((n) => n.isPinned).slice(0, maxResults).map((m) => ({
      title: m.title,
      snippet: m.content.slice(0, 180),
      category: m.category
    }));
  }

  /**
   * Saves a newly discovered code snippet or technical note directly into vault & triggers re-index
   */
  public static recordTechnicalDiscovery(title: string, content: string, tags: string[] = ['discovery', 'code']): StonicxTopicNote {
    const notes = loadStonicxTopicNotes();
    const newNote: StonicxTopicNote = {
      id: `stx-note-discovery-${Date.now()}`,
      title,
      category: 'code',
      content,
      tags,
      lastModified: Date.now(),
      isPinned: false
    };

    const updated = [newNote, ...notes];
    saveStonicxTopicNotes(updated);
    this.autoIndexSessionState();
    return newNote;
  }
}
